# Site Info
title:              "MT Rohman - IoT Enthusiast and Web Developer"
description:        "Writing things, sharing and learning together"
google_verify:      google486e230e3b0ebd08 # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "mtrohman" # Your name here
author_email:       me@mtrohman.com # Your email here
author_gravatar:    860028d64272ebc9b32de42be27c4817 # Gravatar md5 hash
twitter_username:   mtrohman
github_username:    mtrohman # Your GitHub username here

# Site Settings
baseurl:            "/blog" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:title # Post permalink
timezone:           Asia/Jakarta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
